---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf-#{DEPLOYMENT_SUFFIX}#
  namespace: "#{DEPLOYMENT_NAMESPACE}#"
  labels:
    app: opentelemetry
    component: otel-collector-conf-#{DEPLOYMENT_SUFFIX}#
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      jaeger:
        protocols:
          grpc:
          thrift_http:
          thrift_binary:
          thrift_compact:
      zipkin: {}
      opencensus: {}
    processors:
      batch:
      memory_limiter:
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 683
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      health_check: {}
      zpages: {}
    exporters:
      logging:
        loglevel: debug
        # loglevel: info
      azuremonitor:
        instrumentation_key: #{APP-INSIGHTS-INSTRUMENTATION-KEY}#
        endpoint: "#{APP-INSIGHTS-INSTRUMENTATION-URL}#/v2/track"
        maxbatchsize: 1024
        maxbatchinterval: 10s
    service:
      extensions: [health_check, zpages]
      pipelines:
        traces:
          receivers: [otlp, jaeger, zipkin, opencensus]
          processors: [memory_limiter, batch]
          exporters: [logging, azuremonitor]
        # metrics:
        #   receivers: [otlp, jaeger, zipkin]
        #   processors: [memory_limiter, batch, queued_retry]
        #   exporters: [logging]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-#{DEPLOYMENT_SUFFIX}#
  namespace: "#{DEPLOYMENT_NAMESPACE}#"
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector-#{DEPLOYMENT_SUFFIX}#
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector-#{DEPLOYMENT_SUFFIX}#
    spec:
      containers:
      - command:
          - "/otelcontribcol"
          - "--config=/conf/otel-collector-config.yaml"
#           Memory Ballast size should be max 1/3 to 1/2 of memory.
          - "--mem-ballast-size-mib=683"
        image: otel/opentelemetry-collector-contrib:latest
        name: otel-collector
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 55679 # Default endpoint for ZPages.
          protocol: TCP
        - containerPort: 55680 # Default endpoint for OpenTelemetry receiver GRPC.
          protocol: TCP
        - containerPort: 55681 # Default endpoint for OpenTelemetry receiver HTTP.
          protocol: TCP
        - containerPort: 14250 # Default endpoint for Jaeger HTTP receiver.
          protocol: TCP
        - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
          protocol: TCP
        - containerPort: 9411 # Default endpoint for Zipkin receiver.
          protocol: TCP
        - containerPort: 8888  # Default endpoint for querying metrics.
          protocol: TCP
        - containerPort: 55678  # Default endpoint for Opencensus.
          protocol: TCP
        volumeMounts:
        - name: otel-collector-config-vol-#{DEPLOYMENT_SUFFIX}#
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
            scheme: HTTP
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
            scheme: HTTP
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
        - configMap:
            name: otel-collector-conf-#{DEPLOYMENT_SUFFIX}#
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol-#{DEPLOYMENT_SUFFIX}#
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-#{DEPLOYMENT_SUFFIX}#
  namespace: "#{DEPLOYMENT_NAMESPACE}#"
  labels:
    app: opentelemetry
    component: otel-collector-#{DEPLOYMENT_SUFFIX}#
spec:
  selector:
    component: otel-collector-#{DEPLOYMENT_SUFFIX}#
  ports:
  - name: tcp-otlp # Default endpoint for OpenTelemetry receiver.
    port: 55680
    protocol: TCP
    targetPort: 55680
  - name: http # Default endpoint for OpenTelemetry receiver.
    port: 55681
    protocol: TCP
    targetPort: 55681
  - name: tcp-jaeger-grpc # Default endpoing for Jaeger gRPC receiver
    port: 14250
  - name: tcp-jaeger-thrift-http # Default endpoint for Jaeger HTTP receiver.
    port: 14268
  - name: tcp-zipkin # Default endpoint for Zipkin receiver.
    port: 9411
  - name: tcp-metrics # Default endpoint for querying metrics.
    port: 8888
  - name: tcp-opencensus # Default endpoint for querying metrics.
    port: 55678
# For autoscaling --- begin
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: otel-collector-#{DEPLOYMENT_SUFFIX}#
  namespace: "#{DEPLOYMENT_NAMESPACE}#"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: otel-collector-#{DEPLOYMENT_SUFFIX}#
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
# For autoscaling --- end