apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "external-certificate-#{DEPLOYMENT_SUFFIX}#"
  namespace: "#{DEPLOYMENT_NAMESPACE}#"
spec:
  secretName: "external-certificate-#{DEPLOYMENT_SUFFIX}#"
  renewBefore: 2h
  dnsNames:
  - "#{SUB_DOMAIN_NAME_PORTAL}#.eastus.cloudapp.azure.com"
  issuerRef:
    name: letsencrypt-prod-istio
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    group: cert-manager.io